Repository bitovi/bitops, pull requests merged in 2022-08, with the labels that each got.

#236 Validation & Error reporting for bitops.config.yam top yaml level
  scripts/plugins/settings.py
Labels: bug

#242 Fix plugins install not returning correct exit code on failure
  scripts/plugins/install_plugins.py
Labels: bug

#223 Add GitHub star button to the docs page
  docs/index.md
Labels: documentation, enhancement

#263 Remove unused v1 GH job for master branch
  .github/workflows/build-and-publish.yml
Labels: enhancement, CI/CD

#265 Fix 'base' image docker tagging
  .github/workflows/build-and-publish-base.yaml
  scripts/ci/publish.sh
Labels: bug, CI/CD

#276 ff
  .DS_Store
  .github/workflows/build-and-publish-base.yaml
  docs/about.md
  docs/contributing.md
  docs/default-environment.md
  docs/getting-started.md
  docs/index.md
  docs/operations-repo-structure.md
  docs/tool-configuration/configuration-terraform.md
  mkdocs.yml
  scripts/ci/publish.sh
Labels: bug

#273 Updating splash about
  docs/index.md
Labels: documentation, enhancement

#269 Fix missing ENVIRONMENT -> BITOPS_ENVIRONMENT var changes in the docs
  docs/configuration-base.md
  docs/default-environment.md
  docs/development-local.md
  docs/development/development.md
  docs/examples.md
  docs/operations-repo-structure.md
Labels: documentation

#268 Fix deploy_plugins to exit with non-zero return code on error
  scripts/plugins/deploy_plugins.py
Labels: bug

#267 Build and deploy 'dev' image for omnibus
  .github/workflows/build-and-publish-prebuilt.yaml
  prebuilt-config/bitops-tag.yaml
  prebuilt-config/dockerfile.template
Labels: CI/CD

#274 Add GH Discussions badge
  README.md
  docs/index.md
Labels: documentation, enhancement

#277 Add a deprecation warning for 'ENVIRONMENT' & env fallback
  scripts/plugins/deploy_plugins.py
  scripts/plugins/settings.py
Labels: enhancement

#278 Document the stabilized BitOps versioning in the docs
  docs/about.md
  docs/getting-started.md
  docs/migration/2.0-migration.md
  docs/versioning.md
  mkdocs.yml
Labels: documentation, enhancement

#279 Remove inexistent ENV vars from the docs
  docs/configuration-base.md
Labels: bug, documentation

#284 Development guide fixes
  docs/development/development.md
Labels: bug, documentation, enhancement

#281 Various documentation fixes
  docs/cloud-configuration/configuration-aws.md
  docs/configuration-base.md
  docs/default-environment.md
  docs/development-local.md
  docs/development/development.md
  docs/examples.md
  docs/getting-started.md
  docs/lifecycle.md
  docs/migration/2.0-migration.md
  docs/operations-repo-structure.md
  docs/plugins.md
  docs/tool-configuration/configuration-ansible.md
  docs/tool-configuration/configuration-cloudformation.md
  docs/tool-configuration/configuration-helm.md
  docs/tool-configuration/configuration-terraform.md
  docs/versioning.md
  mkdocs.yml
Labels: documentation

#292 Fix the prebuilt image push and tagging via manual workflow dispatch
  .github/workflows/build-and-publish-prebuilt.yaml
  scripts/ci/publish.sh
Labels: bug, CI/CD
