Repository bitovi/bitops, pull requests merged in 2022-10, with the labels that each got.

#257 Add weekly status calls note to contributing doc
  docs/contributing.md
Labels: documentation 📗

#311 Exit with error when bitops.config.yaml not found
  scripts/plugins/utilities.py
Labels: bug 🪲

#309 Add Docker pulls badge to the README
  README.md
  docs/index.md
Labels: documentation 📗

#314 Add exit_code to the messages doc and some logging improvements
  .gitignore
  scripts/plugins.py
  scripts/plugins/deploy_plugins.py
  scripts/plugins/doc.py
  scripts/plugins/documentation.json
  scripts/plugins/install_plugins.py
  scripts/plugins/utilities.py
Labels: bug 🪲, enhancement ✨

#330 Adjusted helm upgrade docs for k8s fetch
  docs/migration/2.0-migration.md
Labels: documentation 📗

#335 Update v2 migration doc with the correct 'cli' definition in the bitops config
  docs/migration/2.0-migration.md
Labels: documentation 📗

#298 Add Pylint as a python static code analyzer
  .github/workflows/ci.yaml
  .pylintrc
  Dockerfile
  README.md
  docs/development/development.md
  pyproject.toml
  requirements.txt
  scripts/main.py
  scripts/plugins.py
  scripts/plugins/__init__.py
  scripts/plugins/deploy_plugins.py
  scripts/plugins/doc.py
  scripts/plugins/install_plugins.py
  scripts/plugins/logging.py
  scripts/plugins/settings.py
  scripts/plugins/utilities.py
  test-requirements.txt
  tox.ini
Labels: feature, CI/CD, refactor
