Repository bitovi/bitops, pull requests merged in 2022-11, with the labels that each got.

#323 Docs: Roadmap page
  docs/roadmap.md
  mkdocs.yml
Labels: documentation 📗

#340 Plugins configuration docs - format parameters as a table
  docs/cloud-configuration/configuration-aws.md
  docs/cloud-configuration/configuration-azure.md
  docs/cloud-configuration/configuration-gcp.md
  docs/configuration-base.md
  docs/development-local.md
  docs/tool-configuration/bitops.schema.md
  docs/tool-configuration/configuration-ansible.md
  docs/tool-configuration/configuration-cloudformation.md
  docs/tool-configuration/configuration-helm.md
  docs/tool-configuration/configuration-terraform.md
Labels: documentation 📗, enhancement ✨

#352 Fix BitOps failing on empty plugin config sub-items
  scripts/plugins/utilities.py
Labels: bug 🪲

#350 Fix error when there's an empty 'mask' in bitops config
  scripts/plugins/logging.py
Labels: bug 🪲

#355 Adding `BITOPS_PLUGIN_NAME` env passed to the plugin during deploy stage
  scripts/plugins/deploy_plugins.py
Labels: enhancement ✨

#354 Update plugins doc with the correct _SKIP_DEPLOY ENV vars
  docs/development-local.md
  docs/examples.md
  docs/examples/bitops+fast+react+static+renderer/_scripts/deploy/deploy.sh
  docs/tool-configuration/configuration-ansible.md
  docs/tool-configuration/configuration-cloudformation.md
  docs/tool-configuration/configuration-helm.md
  docs/tool-configuration/configuration-terraform.md
Labels: documentation 📗, plugins

#359 CI/CD: Fix Docker :dev tag publish for the 'main' branch updates
  .github/workflows/build-and-publish-prebuilt.yaml
Labels: bug 🪲, CI/CD

#347 Updating install_plugins and settings file with installed_plugins path
  docs/plugins.md
  scripts/plugins/deploy_plugins.py
  scripts/plugins/install_plugins.py
  scripts/plugins/settings.py
Labels: bug 🪲

#356 Prepare release history for the upcoming v2.2.0
  docs/roadmap.md
Labels: type:release

#363 Updating `stack-action` for Terraform and Cloudformation
  docs/migration.md
  docs/tool-configuration/configuration-cloudformation.md
  docs/tool-configuration/configuration-terraform.md
  mkdocs.yml
Labels: documentation 📗
