Repository bitovi/bitops, pull requests merged in 2022-12, with the labels that each got.

#369 Terraform+Ansible blog fixes
  docs/examples/bitops+terraform+ansible-blog/README.md
  docs/examples/bitops+terraform+ansible-blog/test/ansible/bitops.config.yaml
  docs/examples/bitops+terraform+ansible-blog/test/ansible/inventory.yml
  docs/examples/bitops+terraform+ansible-blog/test/ansible/playbook.yaml
  docs/examples/bitops+terraform+ansible-blog/test/terraform/bitops.config.yaml
  docs/examples/bitops+terraform+ansible-blog/test/terraform/main.tf
Labels: documentation 📗, blog

#372 Docs update for Ansible 'main-playbook: playbook.yaml' new default
  docs/tool-configuration/configuration-ansible.md
Labels: documentation 📗

#368 Exit with the error on unsupported bitops schema data type in fail_fast mode
  scripts/plugins/utilities.py
Labels: bug 🪲

#373 Fix plugin deploy to respect return code from invoked bash scripts
  scripts/plugins/deploy_plugins.py
  scripts/plugins/install_plugins.py
  scripts/plugins/utilities.py
Labels: bug 🪲

#379 Fix BitOps to pass lowercase booleans based on plugin schema defaults
  scripts/plugins/utilities.py
Labels: bug 🪲

#376 Add problem matchers to highlight errors in Github PRs code diff
  .github/matchers/black.json
  .github/matchers/pylint.json
  .github/workflows/ci.yaml
  scripts/plugins/settings.py
Labels: enhancement ✨, tests, CI/CD

#378 Update roadmap for v2.3 release
  docs/roadmap.md
Labels: documentation 📗

#349 Local plugin install
  Dockerfile
  docs/development/local-plugin-creation.md
  docs/examples/plugin-examples/plugin-install/duplicate-environment/bitops.before-deploy.d/example-before-script.sh
  docs/examples/plugin-examples/plugin-install/duplicate-environment/bitops.config.yaml
  docs/examples/plugin-examples/plugin-no-install/duplicate-environment/bitops-level/bitops.config.yaml
  docs/examples/plugin-examples/plugin-no-install/duplicate-environment/bitops.before-deploy.d/example-before-script.sh
  docs/examples/plugin-examples/plugin-no-install/duplicate-environment/bitops.config.yaml
  docs/plugins.md
  scripts/plugins/install_plugins.py
Labels: feature

#381 Update documentation for secrets masking
  docs/plugins.md
  prebuilt-config/aws-ansible/bitops.config.yaml
  prebuilt-config/aws-helm/bitops.config.yaml
  prebuilt-config/aws-terraform/bitops.config.yaml
  prebuilt-config/example-plugin/bitops.config.yaml
  prebuilt-config/omnibus/bitops.config.yaml
Labels: documentation 📗
