Repository bitovi/bitops, pull requests merged in 2022-09, with the labels that each got.

#297 Reformat python code with black
  .github/workflows/ci.yaml
  .gitignore
  README.md
  docs/contributing.md
  docs/development/development.md
  docs/index.md
  pyproject.toml
  scripts/plugins.py
  scripts/plugins/__init__.py
  scripts/plugins/deploy_plugins.py
  scripts/plugins/doc.py
  scripts/plugins/install_plugins.py
  scripts/plugins/logging.py
  scripts/plugins/settings.py
  scripts/plugins/utilities.py
  test-requirements.txt
  tox.ini
Labels: enhancement, feature, CI/CD

#299 Example update: Getting started with BitOps v2.0 - Terraform
  .gitignore
  docs/examples/bitops2-terraform-blog/README.md
  docs/examples/bitops2-terraform-blog/_default/_tf_modules/eks/createcluster.tf
  docs/examples/bitops2-terraform-blog/_default/_tf_modules/eks/variables.tf
  docs/examples/bitops2-terraform-blog/test/terraform/bitops.config.yaml
  docs/examples/bitops2-terraform-blog/test/terraform/main.tf
  docs/examples/bitops2-terraform-blog/test/terraform/test-vars.auto.tfvars.json
  docs/examples/bitops2-terraform-blog/test/terraform/variables.tf
Labels: documentation, examples

#300 Fix the CI status not showing for the main branch
  .github/workflows/ci.yaml
  README.md
Labels: bug, CI/CD
